const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Plugins.Date,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.advert,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.Reverse,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right
	];
};
self.C3_JsPropNameTable = [
	{Option1: 0},
	{Option2: 0},
	{Option3: 0},
	{Option4: 0},
	{Option5: 0},
	{Option6: 0},
	{Tween: 0},
	{TiledBackground2: 0},
	{BG: 0},
	{DermaQuest_Logo: 0},
	{Shape_: 0},
	{Text_Timer: 0},
	{Audio: 0},
	{Browser: 0},
	{ArrayQuestionNumber: 0},
	{TextDebug_QuestionNumber: 0},
	{play: 0},
	{Touch: 0},
	{TextDebug_QuestionArray: 0},
	{TextDebug_ArrayWidth: 0},
	{smile: 0},
	{TextBox_ThankYou: 0},
	{Button_Explore: 0},
	{Text_Home_ThankYou: 0},
	{Text_Home_ThankYou2: 0},
	{Text_Home_ThankYou3: 0},
	{home_Button: 0},
	{Text_HowTo_1: 0},
	{Text_HowTo_Start: 0},
	{Shape_2: 0},
	{Button_Start: 0},
	{Clock: 0},
	{Text: 0},
	{Fade: 0},
	{correct: 0},
	{incorrect: 0},
	{dialogue: 0},
	{Sprite3: 0},
	{header: 0},
	{ok_btn: 0},
	{Reward: 0},
	{ScreenshotItAndShowAtThePaymentCounterForDiscount: 0},
	{Shape: 0},
	{Text_Score_1: 0},
	{Sprite4: 0},
	{Text_Score_2: 0},
	{Mute: 0},
	{Text_Mute: 0},
	{BannerTimer: 0},
	{Box_White_Option1: 0},
	{Box_White_Situation: 0},
	{Box_Yellow_TreatmentNo: 0},
	{Box_Blue_OptionTitle1: 0},
	{Text_T1_1: 0},
	{Text_T1_2: 0},
	{Text_T1_4: 0},
	{Text_T1_3: 0},
	{Text2: 0},
	{Text_T1_Title: 0},
	{Treatment: 0},
	{Button_Next: 0},
	{Text_Next: 0},
	{Box_White_ExpInfo: 0},
	{Box_Blue_ExpTitle: 0},
	{Text_ExpTitle: 0},
	{Text_Explanation: 0},
	{Box_White_Option2: 0},
	{Box_White_Option3: 0},
	{Box_White_Option4: 0},
	{right_answer: 0},
	{wrong_answer: 0},
	{Score: 0},
	{Text_Diamond_Score: 0},
	{Box_Blue_OptionTitle2: 0},
	{Box_Blue_OptionTitle3: 0},
	{Box_Blue_OptionTitle4: 0},
	{Text_Final_Score: 0},
	{Text_BetterLuck: 0},
	{opps: 0},
	{Text_Date: 0},
	{Date: 0},
	{Text_Reward: 0},
	{Button_Back: 0},
	{AJAX: 0},
	{JSON: 0},
	{Email_Id: 0},
	{Name: 0},
	{Phone: 0},
	{Submit: 0},
	{TiledBackground3: 0},
	{Sprite: 0},
	{ok_btn2: 0},
	{StarID: 0},
	{Star: 0},
	{Text4: 0},
	{Text3: 0},
	{enabled: 0},
	{Submit_2: 0},
	{Submit_user: 0},
	{Sprite2: 0},
	{MobileAdvert: 0},
	{Mouse: 0},
	{TFamily_Home: 0},
	{Family_Text_Home: 0},
	{canPlay: 0},
	{maxTimer: 0},
	{play_time: 0},
	{currentQuestion: 0},
	{OptionNumberChosen: 0},
	{correctAnswer: 0},
	{currentHealth: 0},
	{questionsRemaining: 0},
	{Email: 0},
	{UserName: 0},
	{PhoneNumber: 0},
	{MongoId: 0},
	{FinalScore: 0},
	{SelectedRating: 0},
	{timerCount: 0},
	{QuestionNumber: 0},
	{optionNo: 0},
	{Correct: 0},
	{isTimeUp: 0},
	{currentQues: 0},
	{ansCorrect: 0},
	{Increase: 0},
	{Discount: 0}
];

self.InstanceType = {
	Option1: class extends self.ISpriteInstance {},
	Option2: class extends self.ISpriteInstance {},
	Option3: class extends self.ISpriteInstance {},
	Option4: class extends self.ISpriteInstance {},
	Option5: class extends self.ISpriteInstance {},
	Option6: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	BG: class extends self.ISpriteInstance {},
	DermaQuest_Logo: class extends self.ISpriteInstance {},
	Shape_: class extends self.ISpriteInstance {},
	Text_Timer: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ArrayQuestionNumber: class extends self.IArrayInstance {},
	TextDebug_QuestionNumber: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TextDebug_QuestionArray: class extends self.ITextInstance {},
	TextDebug_ArrayWidth: class extends self.ITextInstance {},
	smile: class extends self.ISpriteInstance {},
	TextBox_ThankYou: class extends self.ISpriteInstance {},
	Button_Explore: class extends self.ISpriteInstance {},
	Text_Home_ThankYou: class extends self.ITextInstance {},
	Text_Home_ThankYou2: class extends self.ITextInstance {},
	Text_Home_ThankYou3: class extends self.ITextInstance {},
	home_Button: class extends self.ISpriteInstance {},
	Text_HowTo_1: class extends self.ITextInstance {},
	Text_HowTo_Start: class extends self.ITextInstance {},
	Shape_2: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	correct: class extends self.ISpriteInstance {},
	incorrect: class extends self.ISpriteInstance {},
	dialogue: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	header: class extends self.ISpriteInstance {},
	ok_btn: class extends self.ISpriteInstance {},
	Reward: class extends self.ISpriteInstance {},
	ScreenshotItAndShowAtThePaymentCounterForDiscount: class extends self.ISpriteInstance {},
	Shape: class extends self.ISpriteInstance {},
	Text_Score_1: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text_Score_2: class extends self.ITextInstance {},
	Mute: class extends self.ISpriteInstance {},
	Text_Mute: class extends self.ITextInstance {},
	BannerTimer: class extends self.ISpriteInstance {},
	Box_White_Option1: class extends self.ISpriteInstance {},
	Box_White_Situation: class extends self.ISpriteInstance {},
	Box_Yellow_TreatmentNo: class extends self.ISpriteInstance {},
	Box_Blue_OptionTitle1: class extends self.ISpriteInstance {},
	Text_T1_1: class extends self.ITextInstance {},
	Text_T1_2: class extends self.ITextInstance {},
	Text_T1_4: class extends self.ITextInstance {},
	Text_T1_3: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text_T1_Title: class extends self.ITextInstance {},
	Treatment: class extends self.ISpriteInstance {},
	Button_Next: class extends self.ISpriteInstance {},
	Text_Next: class extends self.ITextInstance {},
	Box_White_ExpInfo: class extends self.ISpriteInstance {},
	Box_Blue_ExpTitle: class extends self.ISpriteInstance {},
	Text_ExpTitle: class extends self.ITextInstance {},
	Text_Explanation: class extends self.ITextInstance {},
	Box_White_Option2: class extends self.ISpriteInstance {},
	Box_White_Option3: class extends self.ISpriteInstance {},
	Box_White_Option4: class extends self.ISpriteInstance {},
	right_answer: class extends self.ISpriteInstance {},
	wrong_answer: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	Text_Diamond_Score: class extends self.ITextInstance {},
	Box_Blue_OptionTitle2: class extends self.ISpriteInstance {},
	Box_Blue_OptionTitle3: class extends self.ISpriteInstance {},
	Box_Blue_OptionTitle4: class extends self.ISpriteInstance {},
	Text_Final_Score: class extends self.ITextInstance {},
	Text_BetterLuck: class extends self.ITextInstance {},
	opps: class extends self.ISpriteInstance {},
	Text_Date: class extends self.ITextInstance {},
	Date: class extends self.IInstance {},
	Text_Reward: class extends self.ITextInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Email_Id: class extends self.ITextInputInstance {},
	Name: class extends self.ITextInputInstance {},
	Phone: class extends self.ITextInputInstance {},
	Submit: class extends self.IButtonInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ok_btn2: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Submit_2: class extends self.ISpriteInstance {},
	Submit_user: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MobileAdvert: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TFamily_Home: class extends self.ISpriteInstance {},
	Family_Text_Home: class extends self.ITextInstance {}
}